In [1]:
!pip install numpy
#pip python installing package

In [3]:
import numpy as np
# as - alias - nickname

In [50]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [51]:
#2d array
b=np.array([[1,2,3],[4,5,6]])

In [52]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
#3d array

In [54]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [55]:
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
d=np.array([[1,2,3,5],[4,5,6,5],[7,8,9,6],[7,6,4,6]])

In [57]:
d

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 6],
       [7, 6, 4, 6]])

Attributes

In [58]:
a.ndim

1

In [59]:
b.ndim

2

In [60]:
c.ndim

3

In [61]:
d.ndim

2

In [62]:
c.shape

(2, 2, 3)

In [63]:
a.shape

(3,)

In [64]:
d.shape

(4, 4)

In [77]:
arr=np.array([True,22])

In [78]:
np.array([None,34])

array([None, 34], dtype=object)

In [79]:
print(np.array)

<built-in function array>


In [80]:
a.size

3

In [81]:
c.size

12

In [82]:
# .dtype

In [83]:
a.dtype

dtype('int64')

In [84]:
arr.dtype

dtype('int64')

In [85]:
arr=np.array([20,30,40], dtype= np.int16)

In [86]:
arr

array([20, 30, 40], dtype=int16)

- int- positive - whole no- int8, int32, int64
- only positive - unsigned integer- np.uint8, np.uint16, 32,
- float for decimal- float16, 32, 64
- boolean- ture, false - np.bool_
- string - np.string_
- object - Mix data type - np.object_

In [87]:
a

array([10, 20, 30])

In [88]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
b.T   # .T transpose the array

array([[1, 4],
       [2, 5],
       [3, 6]])

Methods

In [92]:
# np.random.rand() - random float create between 0 to 1

In [93]:
np.random.rand()

0.7298984093835537

In [94]:
np.random.rand(3)

array([0.05689717, 0.86426264, 0.45975699])

In [97]:
np.random.rand(3,3)

array([[0.29080712, 0.20701557, 0.3173188 ],
       [0.8874629 , 0.26820321, 0.81890584],
       [0.72274514, 0.45976156, 0.41978218]])

In [100]:
# np.random.randn() -cretae  strandard normal distribution
# where mean always =0 and standard deviation =1

In [103]:
np.random.randn(5)

array([-1.94914317, -1.17129982,  1.66952038,  1.59535049, -0.20066565])

In [104]:
np.random.randn(3,5)

array([[-0.50501847,  0.72539483,  0.17189181, -0.5933186 , -0.99196014],
       [ 0.62908842, -0.07259459, -0.18852971,  0.4902294 , -0.58670581],
       [-1.18720083, -1.43501886, -0.44909845, -1.67133735, -1.20256407]])

In [130]:
# random.randint - where we given range

In [131]:
np.random.randint(1,10) # single random element between  1 to 11

1

In [132]:
np.random.randint(10) ## range 0 to 9

5

In [135]:
np.random.randint(10, size=5) # range 0 to 9

array([2, 2, 7, 4, 8])

Indexing and slicing in array

In [136]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [140]:
print(arr[0])

1


In [142]:
print(arr[-5])

5


In [153]:
arr1=np.array([[1,2,3],[4,5,6]])

In [154]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
print(arr1[0][1])

2


In [156]:
print(arr1[1][1])

5


In [157]:
# Slicing

In [158]:
print(arr1[1,1])

5


In [161]:
print(arr1[0:2,1:3])

[[2 3]
 [5 6]]


In [163]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
# Agrrigation function

In [165]:
np.sum(arr1)

np.int64(21)

In [166]:
print(np.mean(arr1))

3.5


In [167]:
print(np.median(arr1))

3.5


In [168]:
print(np.std(arr1))

1.707825127659933


In [169]:
print(np.var(arr1))

2.9166666666666665


In [170]:
print(np.min(arr1))

1


In [171]:
print(np.max(arr1))

6


In [172]:
print(np.argmin(arr1))

0


In [173]:
print(np.argmax(arr1))

5


In [174]:
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [175]:
print(np.log(arr1))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [176]:
print(np.log10(arr1))

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]


In [177]:
print(np.exp(arr1))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [178]:
print(np.sin(arr1))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [182]:
print(np.cos(arr1))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [185]:
# .reshape

In [186]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [187]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])